version: "3.0"
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=loja
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /home/samuel/dev/fontes/alura/kubernetes/volume:/var/lib/mysql
  web:
    image: rafanercessian/aplicacao-loja:v1
    ports:
      - 8080:80
    depends_on:
      - db